### PR TITLE
Clarify info message for when default account is used

### LINKED ISSUE #9: Inconsistent/confusing behaviour between commands when no --sender account is specified
For most commands, if a required parameter is missing, this will be clearly communicated to the user. For example, a `transaction send-gtu` command with no `--receiver` parameter will print

```
Missing: --receiver RECEIVER-ACCOUNT

Usage: concordium-client.exe transaction send-gtu --receiver RECEIVER-ACCOUNT --amount GTU-AMOUNT
                                                  [--sender SENDER] [--keys KEYS] [--signers SIGNERS]
                                                  [--nonce NONCE] [--energy MAX-ENERGY] [--expiry EXPIRY]
                                                  [--no-confirm] [--no-wait]
  Transfer GTU from one account to another.
```

However for some commands, if the `--sender` parameter is missing, it will instead try and use a default account, and if this default account is not found, it will throw an error

```
Account reference not provided; using "default".
Error: The identifier 'default' is neither the address nor the name of an account.
```

This could be made more informative by also informing the user that the `--sender` parameter is not set.

### PR DESCRIPTION
**Pull request by Bargsteen**
## Purpose

Clarify the info and error messages written when the `default` account is used. 
Closes #9.

## Changes

- Clarify the info message printer to include the argument/flag omission.
- Provide a better error message when the argument/flag was omitted, but no default account exists (this was particularly confusing).
- I've tried to phrase the info and error messages so that the default-account feature can be discovered by accident.
- Remove an unneeded `Maybe`. 

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

File: src/Concordium/Client/Runner.hs [hunk 1]
```diff
@@ -170,10 +170,10 @@ getFromJsonAndHandleError handleError r = do
 
 -- |Look up account from the provided name or address. If 'Nothing' is given, use the defaultAcccountName.
 -- Fail if the address cannot be found.
--- Should be kept consistent with processAccountCmd for AccountShow
 getAccountAddressArg :: AccountNameMap -> Maybe Text -> IO NamedAddress
-getAccountAddressArg m input =
-  case getAccountAddress m $ fromMaybe defaultAccountName input of
+getAccountAddressArg m input = do
```
Comment (abizjak) [inline src/Concordium/Client/Runner.hs:174]: As far as I can tell this function is only ever used with the second argument being `Just _`. So it can be simplified.

File: src/Concordium/Client/Config.hs [hunk 2]
```diff
@@ -841,11 +841,7 @@ getAccountConfig :: Maybe Text
...
                  -> IO (BaseConfig, AccountConfig)
 getAccountConfig account baseCfg keysDir keyMap encKey autoInit = do
-  account' <- case account of
-    Nothing -> do
-      logInfo [printf "account reference not provided; using \"%s\"" defaultAccountName]
-      return defaultAccountName
-    Just a -> return a
+  account' <- getAccountOrDefault account
   namedAddr <- case getAccountAddress (bcAccountNameMap baseCfg) account' of
                  Left err -> logFatal [err]
```
Comment (abizjak) [inline src/Concordium/Client/Config.hs:846]: Perhaps it would be useful to revise the error message here in case we attempted to use the "default" account.
We could make it less confusing.
