### PR TITLE
Warn when adding baker with stake below threshold

### LINKED ISSUE #80: Client should warn about insufficient stake when registering a baker
**Description**
Client should warn when registering as baker with insufficient stake. Right now, the transaction fails eventually without warning. In contrast, when updating stake, it talks a lot about the correct amount etc.

stake too low

**Steps to Reproduce**
- register as baker with insufficient stake

**Expected Result**
Client informs before submitting to chain.

**Actual Result**
Client does not warn before submitting to chain.

**Versions**
- CLI 1.1.1-0
- Windows

### PR DESCRIPTION
**Pull request by Bargsteen**
## Purpose

Warn the user when attempting to add a baker with a stake amount lower than the minimum threshold.
Closes #80 

## Changes

- Add function for fetching the minimum threshold from chain
- Warn the user if the staked amount is below the threshold
- Update changelog

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

File: src/Concordium/Client/Runner.hs [hunk 1]
```diff
@@ -1257,6 +1257,15 @@ bakerAddTransaction baseCfg txOpts f batcBakingStake batcRestakeEarnings confirm
           Just x -> return x
           Nothing -> logFatal [err]
 
+-- |Query the chain for the minimum baker stake threshold. Fail if the chain cannot be reached.
+getBakerStakeThresholdOrDie :: ClientMonad IO Types.Amount
+getBakerStakeThresholdOrDie = do
+  blockSummary <- getFromJson =<< withBestBlockHash Nothing getBlockSummary
```
Comment (abizjak) [inline src/Concordium/Client/Runner.hs:1263]:
```suggestion
  blockSummary <- getFromJson =<< withLastFinalBlockHash Nothing getBlockSummary
```
To make it more robust.

File: src/Concordium/Client/Runner.hs [hunk 2]
```diff
@@ -1257,6 +1257,15 @@ bakerAddTransaction baseCfg txOpts f batcBakingStake batcRestakeEarnings confirm
...
+  case blockSummary of
+    Nothing -> do
+      logFatal ["No Block Found"]
```
Comment (abizjak) [inline src/Concordium/Client/Runner.hs:1266]: Please make a better error message. Perhaps
```
Could not reach the node to retrieve baker stake threshold.
```

File: src/Concordium/Client/Runner.hs [hunk 3]
```diff
@@ -1257,6 +1257,15 @@ bakerAddTransaction baseCfg txOpts f batcBakingStake batcRestakeEarnings confirm
           Just x -> return x
           Nothing -> logFatal [err]
 
+-- |Query the chain for the minimum baker stake threshold. Fail if the chain cannot be reached.
+getBakerStakeThresholdOrDie :: ClientMonad IO Types.Amount
```
Comment (abizjak) [inline src/Concordium/Client/Runner.hs:1261]: Does this not already exist somewhere?

File: src/Concordium/Client/Runner.hs (hunk 2 above)
Comment (Bargsteen) [reply src/Concordium/Client/Runner.hs]: Sounds good. I had matched the message used elsewhere, but I've now clarified those as well.

**Review by abizjak — APPROVED** [review]
