### PR TITLE
Delegation

### LINKED ISSUE #114: Register as baker with `baker add` and `baker configure` fails
**Bug Description**
Trying to register as baker. I used `baker generate-keys` and then `baker add` but it is rejected  with
`Warning: Proof that baker owns relevant private keys is not valid.`

Full command was:
`baker add stagenet10-baker-keys.json --sender "stagenet10" --stake 14000 --open-delegation-for none --delegation-transaction-fee-commission 5.0e-2 --delegation-baking-commission 5.0e-2 --delegation-finalization-commission 1.0 --baker-url baker-url.json --out stagenet10-baker-credentials.json`

**Steps to Reproduce**
- `baker generate-keys` 
- `baker add` 
according to documentation + client help that parameters are missing.

**Expected Result**
Transaction successful.

**Actual Result**
Transaction rejected with `Warning: Proof that baker owns relevant private keys is not valid.`

**Versions**
- concordium-client_4.0.0-delegation-test-0
- Windows

### LINKED ISSUE #118: More info for missing parameters for `baker configure`
**Bug Description**
Currently, when a parameter is missing, the `baker configure` transaction only shows
`Warning: Missing parameters to add new baker.`

This is not sufficient, given that there are 18 options in the documentation via `baker configure -h`, which are not all required.

**Expected Result**
Similar user guidance as in e.g. `baker add`.

**Actual Result**
`Warning: Missing parameters to add new baker.`

**Versions**
- concordium-client_4.0.0-delegation-test-1
- Windows

### LINKED ISSUE #119: More info for wrong commission ranges for `baker configure`
**Bug Description**
Currently, when one commission is missing, the `baker configure` transaction only shows
`Warning: A commission fee was not within the allowed range.`

**Expected Result**
It should give more specific user guidance on which one exactly.

**Actual Result**
`Warning: A commission fee was not within the allowed range.`

**Versions**
- concordium-client_4.0.0-delegation-test-1
- Windows

### LINKED ISSUE #120: baker update-delegation-status all fails
**Bug Description**
`Concordium client baker update-delegation-status all` fails with feedback Invalid argument 'all'.

**Expected Result**
Command should open pool for all delegators.

**Actual Result**
Invalid argument 'all'.

**Versions**
- Software Version: Node 4.0.5-delegation-test-1

### LINKED ISSUE #121: Misleading message for `baker remove`
**Bug Description**
When removing a baker in the concordium-client, there are the following misleading messages, resulting from the fact that deregistering as baker is now the same as decreasing the stake to 0 and thereby below the baker threshold.

```
Warning: The staked amount (0.000000 CCD) is lower than the minimum baker stake threshold (1000.000000 CCD).
This transaction will most likely be rejected by the chain, do you wish to send it anyway [yN]: y
y
Warning: The new staked value appears to be lower than the amount currently staked on chain by this baker.
```

**Expected Result**
When removing a baker/decreasing stake to 0, different warnings should be shown as when just decreasing stake to below baker thresold.

**Actual Result**
Misleading warning that transaction will most likely be rejected.

**Versions**
- concordium-client_4.0.0-delegation-test-1
- Windows

### LINKED ISSUE #122: Client always set restake to true unless `--no-restake` flag is provided
**Bug Description**
Client always assumes that restake is true unless user specifically doesn't provide `--no-restake` flag in every command.

**Steps to Reproduce**
Set the stake with flag `--no-restake` so that rewards are not restaked.
Send another command to increase the stake but don't provide a flag for restaking.

**Expected Result**
Stake should be increased and rewards should not be restaked.

**Actual Result**
Stake was increased but rewards are restaked.

**Versions**
- Software Version: concordium-client_4.0.0-delegation-test-1

### LINKED ISSUE #124: `baker update-delegation-status` does not work as described in documentation
**Bug Description**
Documentation says that syntax is `baker update-delegation-status SELECTION` with `SELECTION = all, existing, none`. However, this does not seem to work.

**Expected Result**
Command works according to documentation, e.g. `baker update-delegation-status all --sender "x"`

**Actual Result**
Invalid argument 

**Versions**
- Windows
- Concordium Client: 4.0.0-delegation-test-1
- Concordium Node: 4.0.5-delegation-test-5

### LINKED ISSUE #125: Text about decreasing stake should be removed when increasing stake:
**Bug Description**
Text about decreasing stake should be removed when increasing stake:
```
Note that decreasing the amount a baker is staking will lock the stake of the baker for a cooldown period before the CCD are made available.
During this period it is not possible to update the baker's stake, or stop the baker.
The current baker cooldown would last until approximately 2022-03-29 16:05:36.0646332 UTC.
```

Note that the exact same text appears correctly as warning when decreasing stake. It has no relevance when increasing stake.

**Expected Result**
No explanation of consequences of decreasing stake when increasing stake.

**Actual Result**
See above.

**Versions**
- Windows
- Concordium Client: 4.0.0-delegation-test-1
- Concordium Node: 4.0.5-delegation-test-5

### LINKED ISSUE #126: `baker configure --stake 0` does not work
**Bug Description**
`baker configure --sender "x" --stake 0` is rejected with `Warning: Remove baker failed because of unexpected parameters.`

Note that extensive warning is dealt with in [#121](https://github.com/Concordium/concordium-client/issues/121)
**Expected Result**
`baker configure --stake 0` works as `baker remove`

**Actual Result**
Rejected with unexpected parameters.

**Versions**
- Windows
- Concordium Client: 4.0.0-delegation-test-1
- Concordium Node: 4.0.5-delegation-test-5

### LINKED ISSUE #127: Too much info for delegation commands
**Bug Description**
For all delegation commands, i.e. `delegator add, remove, configure` there is an unusual amount of info given when submitting and finalizing transactions. It clutters the concordium-client and is not in line with other client commands.

delegting6

**Expected Result**
```
Transaction is committed into block ...
[timestamp] Waiting ...
Transaction is finalized into block ...
```

**Actual Result**
```
Transaction is committed into block ...
delegator added
delegator restake earnings ... 
delegator delegation target ... 
[timestamp] Waiting ...
Transaction is finalized into block ...
```

See screenshot.

**Versions**
- Windows
- Concordium Client: 4.0.0-delegation-test-1
- Concordium Node: 4.0.5-delegation-test-5

### LINKED ISSUE #128: The help message for `raw GetBakerList` is wrong
**Bug Description**
The help message for `raw GetBakerList` is wrong as follows:
`Query the gRPC server for the status of a baker pool or the L-pool.`

**Steps to Reproduce**
Type `concordium-client raw GetBakerList --help`

**Expected Result**
`Query the gRPC server for the list of bakers`

**Actual Result**
`Query the gRPC server for the status of a baker pool or the L-pool.`

**Versions**
- Software Version: `concordium-client_4.0.0-delegation-test-1`
- OS: MacOS
- Browser
- Mobile device, if applicable

### PR DESCRIPTION
**Pull request by eb-concordium**
## Purpose

To implement commands for sending the new transactions that are introduced in Protocol version 4.
To add commands for querying baker pool status, baker list and reward status.

Furthermore:
- Closes #114.
- Closes #118.
- Closes #119.
- Closes #120.
- Closes #121.
- Closes #122.
- Closes #124.
- Closes #125.
- Closes #126.
- Closes #127.
- Closes #128.

## Changes

- The commands `delegator add`, `delegator configure` and `delegator remove` have been added.
- The commands `baker configure` , `baker update-url` and `baker update-delegation-status` have been added. 
- The existing commands `baker add`, `baker remove`, `baker set-key`, `baker update-restake` and `baker update-stake` have been changed so that in Protocol version < 4, they generate the former transaction, and in Protocol version 4, they generate the relevant `configure baker` transaction. 

The functionality is implemented, but some code can be refactored a bit, which is why this PR is currently marked as WIP.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

File: src/Concordium/Client/Commands.hs [hunk 1]
```diff
@@ -1348,10 +1410,71 @@ bakerAddCmd =
...
+        optional (option (eitherReader amountFractionFromStringInform) (long "delegation-baking-commission" <> metavar "DECIMAL-FRACTION" <> help ("Fraction the baker takes in commission from delegators on baking rewards. " ++ rangesHelpString "baking reward commission"))) <*>
+        optional (option (eitherReader amountFractionFromStringInform) (long "delegation-finalization-commission" <> metavar "DECIMAL-FRACTION" <> help ("Fraction the baker takes in commission from delegators on finalization rewards. " ++ rangesHelpString "finalization reward commission"))) <*>
+        optional (
+            (,) <$>
+                strOption (long "keys-in" <> metavar "FILE" <> help "File containing baker credentials.") <*>
+                strOption (long "keys-out" <> metavar "FILE" <> help "File to write updated baker credentials to, in case of successful transaction. These can be used to start the node."))
```
Comment (abizjak) [inline src/Concordium/Client/Commands.hs:1454]: Is there a concrete reason why they are both required or none? This seems different from the `baker add` command which does not require keys-out even if keys-in is present.

File: src/Concordium/Client/Commands.hs [hunk 2]
```diff
@@ -1348,10 +1410,71 @@ bakerAddCmd =
...
+      )
+      (progDesc "Configure baker information on the chain."))
```
Comment (abizjak) [inline src/Concordium/Client/Commands.hs:1456]: Perhaps add a bit longer explanation that this can be used to add, remove, and update the baker.

File: src/Concordium/Client/Commands.hs [hunk 3]
```diff
@@ -1401,6 +1524,57 @@ bakerUpdateStakeCmd =
...
+allowedValuesDelegationTargetAsString =
+    "'Passive' (for passive delegation), BAKERID (delegate stake to baker pool with baker id BAKERID)"
+
+delegationTargetInformString :: String -> Either String DelegationTarget
+delegationTargetInformString "Passive" = Right DelegatePassive
+delegationTargetInformString s
+  | Prelude.all Char.isDigit s =
+    let i = read s :: Integer
+        w = fromIntegral i :: Word64
+    in if fromIntegral w == i
```
Comment (abizjak) [inline src/Concordium/Client/Commands.hs:1537]: I would recommend being more explicit in the check and do
```
if i >= 0 && i <= fromIntegral (maxBound :: Word64)
```

File: src/Concordium/Client/Commands.hs [hunk 4]
```diff
@@ -1401,6 +1524,57 @@ bakerUpdateStakeCmd =
...
+        optional (option (eitherReader delegationTargetInformString) (long "target" <> metavar "TARGET" <> helpDelegationTarget)))
+      (progDesc "Configure delegator information on the chain."))
+
+delegatorRemoveCmd :: Mod CommandFields DelegatorCmd
+delegatorRemoveCmd =
+  command
+    "remove"
+    (info
+      (DelegatorRemove <$> transactionOptsParser)
+      (progDesc "Remove delegator from the chain."))
```
Comment (abizjak) [inline src/Concordium/Client/Commands.hs:1564]: Wouldn't a more apt message be `Stop delegating.`

File: src/Concordium/Client/Runner.hs [hunk 5]
```diff
@@ -2806,6 +3318,9 @@ processLegacyCmd action backend =
     GetIdentityProviders block -> withClient backend $ withBestBlockHash block getIdentityProviders >>= printJSON
     GetAnonymityRevokers block -> withClient backend $ withBestBlockHash block getAnonymityRevokers >>= printJSON
     GetCryptographicParameters block -> withClient backend $ withBestBlockHash block getCryptographicParameters >>= printJSON
+    GetChainParameters -> do
+      bs <- withClient backend $ getFromJson =<< withBestBlockHash Nothing getBlockSummary
+      Queries.bsWithUpdates bs $ const $ printJSONValues . toJSON . Types._currentParameters
```
Comment (abizjak) [inline src/Concordium/Client/Runner.hs:3323]: Why was this added? It does not really fit the rest of the raw commands which just forward the response.

It would be great if there was a high-level command for this, but this one should be removed I think.

File: src/Concordium/Client/Runner.hs [hunk 6]
```diff
@@ -2514,226 +3031,215 @@ processBakerCmd action baseCfgDir verbose backend =
...
+          let allPresent = case (openForDelegation, metadataURL, transactionFeeCommission, bakingRewardCommission, finalizationRewardCommission) of
+                (Just _, Just _, Just _, Just _, Just _) -> True
+                _ -> False
+          when (not allPresent) $ do
+            logWarn $ ["To add a baker, all of the options\n"
+                 ++ "--open-delegation-for,\n"
+                 ++ "--baker-url,\n"
+                 ++ "--delegation-transaction-fee-commission,\n"
+                 ++ "--delegation-baking-commission,\n"
+                 ++ "--delegation-finalization-commission\nmust be present."]
```
Comment (abizjak) [inline src/Concordium/Client/Runner.hs:3051]: It would be great if you printed which ones are missing here.

Something like
```haskell
            logWarn $ ["To add a baker, all options are necessary. The following are missing\n"
                 ++ if isNothing openForDelegation then "--open-delegation-for,\n" else ""
                 ...
```

**Comment by abizjak** [comment]
The raw queries `GetPoolStatus` and `GetBakerList` have not been added yet it seems.

**Comment by abizjak** [comment]
The changelog must be updated.

File: src/Concordium/Client/Runner.hs [hunk 7]
```diff
@@ -2500,6 +2365,683 @@ generateBakerKeys bkBakerId = do
...
+          _ -> do
+            logWarn $ [init ("To add a baker, more options are necessary. The following are missing "
+                  ++ (if isNothing cbCapital then "\n--stake," else "")
+                  ++ (if isNothing cbOpenForDelegation then "\n--open-delegation-for," else "")
+                  ++ (if isNothing inputKeysFile then "\n--keys-in," else "")
+                  ++ (if isNothing metadataURL then "\n--baker-url," else "")
+                  ++ (if isNothing cbTransactionFeeCommission then "\n--delegation-transaction-fee-commission," else "")
+                  ++ (if isNothing cbBakingRewardCommission then "\n--delegation-baking-commission," else "")
+                  ++ (if isNothing cbFinalizationRewardCommission then "\n--delegation-finalization-commission," else ""))
+                  ++ (if isNothing cbRestakeEarnings then ". \nExactly one of the options --restake and --no-restake must be present" else "")]
```
Comment (Bargsteen) [inline src/Concordium/Client/Runner.hs:2423]: Argument handling should be dealt with in `Commands.hs` when possible. My comment in that file has a suggested fix.

File: src/Concordium/Client/Runner.hs [hunk 8]
```diff
@@ -2500,6 +2365,683 @@ generateBakerKeys bkBakerId = do
...
+        unless confirmed exitTransactionCancelled
+      when verbose $ do
+        runPrinter $ printSelectedKeyConfig $ tcEncryptedSigningData
+        putStrLn ""
+      return (bakerKeys, txCfg, payload)
+
+    configureCapitalLogMsg =
+      case cbCapital of
+        Nothing -> []
+        Just capital -> [printf "stake will be %s CCD" (Types.amountToString capital)]
```
Comment (Bargsteen) [inline src/Concordium/Client/Runner.hs:2564]:
```suggestion
        Just capital -> [[i|stake will be #{Types.amountToString capital} CCD|]]
```
When adding new code that uses string interpolation, please use this form (https://hackage.haskell.org/package/string-interpolate). `printf` is not safe.
You don't need to change all the occurrences now. Just use the string-interpolate package in the future ;)

File: src/Concordium/Client/Runner.hs [hunk 9]
```diff
@@ -2500,6 +2365,683 @@ generateBakerKeys bkBakerId = do
...
+    bkwpSignatureVerifyKey = abSignatureVerifyKey,
+    bkwpProofSig = abProofSig,
+    bkwpAggregationVerifyKey = abAggregationVerifyKey,
+    bkwpProofAggregation = abProofAggregation
+  }) <- readInputKeysFile baseCfg
+      let payload = Types.encodePayload Types.AddBaker{..}
+          nrgCost _ = return . Just $ bakerAddEnergyCost $ Types.payloadSize payload
+            -- case cbKeysWithProofs of
+            --             Nothing -> return . Just $ bakerConfigureEnergyCostWithoutKeys (Types.payloadSize payload)
+            --             Just _ -> return . Just $ bakerConfigureEnergyCostWithKeys (Types.payloadSize payload)
```
Comment (Bargsteen) [inline src/Concordium/Client/Runner.hs:2729]: Please delete if no longer needed.

File: src/Concordium/Client/Runner.hs [hunk 10]
```diff
@@ -2537,226 +3079,240 @@ processBakerCmd action baseCfgDir verbose backend =
...
+          let allPresent = case (openForDelegation, metadataURL, transactionFeeCommission, bakingRewardCommission, finalizationRewardCommission) of
+                (Just _, Just _, Just _, Just _, Just _) -> True
+                _ -> False
+          when (not allPresent) $ do
+            logWarn $ [init $ "To add a baker, more options are necessary. The following are missing"
+                 ++ (if isNothing openForDelegation then "\n--open-delegation-for," else "")
+                 ++ (if isNothing metadataURL then "\n--baker-url," else "")
+                 ++ (if isNothing transactionFeeCommission then "\n--delegation-transaction-fee-commission," else "")
+                 ++ (if isNothing bakingRewardCommission then "\n--delegation-baking-commission," else "")
+                 ++ (if isNothing finalizationRewardCommission then "\n--delegation-finalization-commission," else "")]
```
Comment (Bargsteen) [inline src/Concordium/Client/Runner.hs:3099]: Please handle in Commands.hs.

**Review by Bargsteen — APPROVED** [review]
Looks good in general!
The only thing I didn't like was how parameters were being handled in `Runner.hs` when they could be handled more cleanly in `Commands.hs`. Changing this would also produce a nicer error messages, because they would be produced by parser package we are using.

File: src/Concordium/Client/Commands.hs [hunk 11]
```diff
@@ -420,7 +425,12 @@ data BakerCmd
     , baTransactionOpts :: !(TransactionOpts (Maybe Energy))
     , baStake :: !Amount
     , baAutoAddEarnings :: !Bool
-    , outputFile :: Maybe FilePath }
+    , baOpenForDelegation :: !(Maybe OpenStatus)
+    , baMetadataURL :: !(Maybe String)
+    , baTransactionFeeCommission :: !(Maybe AmountFraction)
+    , baBakingRewardCommission :: !(Maybe AmountFraction)
+    , baFinalizationRewardCommission :: !(Maybe AmountFraction)
+    , outputFile :: !(Maybe FilePath) }
```
[the remark this answers is not in the document]
Comment (eb-concordium) [reply src/Concordium/Client/Commands.hs]: Done.

File: src/Concordium/Client/Runner.hs (hunk 7 above)
Comment (eb-concordium) [reply src/Concordium/Client/Runner.hs:2423]: This is not possible, since we are looking up whether the account is a baker or not.
