### PR TITLE
Fix schema parsing

### LINKED ISSUE #164: Incorrect schema parsing in concordium-client
**Bug Description**

Concordium-client does not read schemas correctly in certain cases.

In particular if the schema type contains ULEB or ILEB or ByteArray values then it parses them incorrectly.

The lenghts are parsed in big endian, not in little endian. The result of that is that the client fails to parse the supplied JSON parameters when, e.g., updating a contract.

The example schema and JSON to reproduce are part of PR #165 

The issue was first reported by @ulapcyber

### PR DESCRIPTION
**Pull request by abizjak**
## Purpose

Fixes #164 

## Changes

Fix parsing of schemas.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

File: test/SimpleClientTests/SchemaParsingSpec.hs [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+import qualified Data.ByteString as BS
+import qualified Data.Aeson as AE
+
+import Concordium.Client.Types.Contract.Parameter
+import Concordium.Client.Types.Contract.Schema
+
+import Test.Hspec
+import Test.HUnit
+
+-- Test that parsing a parameter that contains a set, a 32-byte array and an
```
Comment (Bargsteen) [inline test/SimpleClientTests/SchemaParsingSpec.hs:15]: Shouldn't it be uleb128/ileb128 instead of `set`?

**Review by Bargsteen — COMMENTED** [review]
Looks good, I just have a minor comment about the test.

File: test/SimpleClientTests/SchemaParsingSpec.hs (hunk 1 above)
Comment (abizjak) [reply test/SimpleClientTests/SchemaParsingSpec.hs:15]: As we discussed in the office, it is a set.

I have however added a ULEB128 to the test now as well.

**Review by Bargsteen — APPROVED** [review]
